from decouple import config

DATABASE_HOSTNAME = config('DATABASE_HOSTNAME')
DATABASE_PORT = int(config('DATABASE_PORT'))
DATABASE_NAME = config('DATABASE_NAME')
DATABASE_USERNAME = config('DATABASE_USERNAME')
SECRET_KEY = config('SECRET_KEY')
ALGORITHM = config('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = int(config('ACCESS_TOKEN_EXPIRE_MINUTES'))
